title: Haoran Luo's Homepage
page-top-title: Haoran Luo
top-section-bg-text: Stay true to who you are.
home-subtitle: Haoran Luo|njuai
copyright-text: '&copy; Haoran Luo 2023-2025. All Rights Reserved.'
